package dev.jco.upgrades;
import net.minecraft.core.*;import net.minecraft.core.component.DataComponents;import net.minecraft.core.registries.*;import net.minecraft.nbt.*;import net.minecraft.server.level.*;import net.minecraft.world.*;import net.minecraft.world.item.*;import net.minecraft.world.item.component.CustomData;import net.minecraft.world.level.block.*;import net.minecraft.world.phys.Vec3;
public final class Downgrades {
 private static final String ITEM_KEY="jco_upgrade_history";
 private record Pending(CompoundTag history,long tick){}
 private static final java.util.Map<net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>,java.util.Map<Long,Pending>> PENDING=new java.util.HashMap<>();
 public static void detach(ServerLevel level,BlockPos pos){var n=UpgradeData.get(level).history.get(pos.asLong());if(n!=null){var map=PENDING.computeIfAbsent(level.dimension(),key->new java.util.HashMap<>());map.values().removeIf(p->p.tick<level.getGameTime());map.put(pos.asLong(),new Pending(n.copy(),level.getGameTime()));}}
 public static void clear(){PENDING.clear();}
 public static void drops(net.neoforged.neoforge.event.level.BlockDropsEvent event){var level=event.getLevel();var map=PENDING.get(level.dimension());if(map==null)return;var pending=map.remove(event.getPos().asLong());if(pending==null||pending.tick!=level.getGameTime()||!BuiltInRegistries.BLOCK.getKey(event.getState().getBlock()).toString().equals(pending.history.getString("target")))return;
  var item=event.getState().getBlock().asItem();for(var drop:event.getDrops())if(drop.getItem().is(item)){CustomData.update(DataComponents.CUSTOM_DATA,drop.getItem(),tag->tag.put(ITEM_KEY,pending.history.copy()));break;}
 }
 public static void placed(net.neoforged.neoforge.event.level.BlockEvent.EntityPlaceEvent event){if(!(event.getLevel() instanceof ServerLevel level)||!(event.getEntity() instanceof net.minecraft.world.entity.player.Player player))return;var pos=event.getPos();var target=BuiltInRegistries.BLOCK.getKey(event.getPlacedBlock().getBlock()).toString();
  for(var hand:InteractionHand.values()){var stack=player.getItemInHand(hand);var custom=stack.get(DataComponents.CUSTOM_DATA);if(custom==null)continue;var n=custom.copyTag().getCompound(ITEM_KEY);if(n.isEmpty()||!target.equals(n.getString("target"))||!stack.is(event.getPlacedBlock().getBlock().asItem()))continue;var data=UpgradeData.get(level);data.history.put(pos.asLong(),n.copy());data.setDirty();return;}
 }
 public static void remember(ServerLevel level,BlockPos pos,UpgradeDefinition d,UpgradeData.Progress p){
  if(!p.rollbackReady)return;var data=UpgradeData.get(level);var n=new CompoundTag();n.putString("target",p.target);n.put("source",p.sourceState.copy());n.put("data",p.sourceData.copy());n.putString("tool",d.reverseTool());n.putInt("need",d.reverseHits());n.putLong("last",Long.MIN_VALUE);var materials=new ListTag();p.escrow.forEach(s->{if(!s.isEmpty())materials.add(s.save(level.registryAccess()));});n.put("materials",materials);if(data.history.containsKey(pos.asLong()))n.put("previous",data.history.get(pos.asLong()).copy());data.history.put(pos.asLong(),n);data.setDirty();
 }
 public static CompoundTag valid(ServerLevel level,BlockPos pos){var data=UpgradeData.get(level);var n=data.history.get(pos.asLong());if(n==null||UpgradeRuntime.occupied(level,pos)||data.entries.containsKey(pos.asLong()))return new CompoundTag();if(!BuiltInRegistries.BLOCK.getKey(level.getBlockState(pos).getBlock()).toString().equals(n.getString("target")))return new CompoundTag();return n;}
 public static void hit(ServerPlayer p,BlockPos pos){var level=p.serverLevel();var n=valid(level,pos);if(n.isEmpty()||p.isSpectator()||!p.mayBuild()||!level.mayInteract(p,pos)||p.distanceToSqr(Vec3.atCenterOf(pos))>Math.pow(p.blockInteractionRange()+1,2)||!new StackMatcher(n.getString("tool")).matches(p.getMainHandItem()))return;if(!InventorySafety.isEmpty(level.getBlockEntity(pos)))return;long now=level.getGameTime(),last=n.getLong("last");if(last!=Long.MIN_VALUE&&now-last<10)return;
  var data=UpgradeData.get(level);int hits=n.getInt("hits")+1;n.putInt("hits",hits);n.putLong("last",now);data.setDirty();new Feedback().sound("minecraft:block.anvil.hit",.5F,1).particles("minecraft:crit",4,.2,.02).emit(level,Vec3.atCenterOf(pos),p,InteractionHand.MAIN_HAND,p.getMainHandItem(),true);if(hits<n.getInt("need"))return;
  var state=NbtUtils.readBlockState(level.holderLookup(Registries.BLOCK),n.getCompound("source"));UpgradeRuntime.TRANSFORMING.set(true);try{if(!level.getBlockState(pos).equals(state)&&!level.setBlock(pos,state,3)){n.putInt("hits",hits-1);return;}var be=level.getBlockEntity(pos);if(be!=null){be.loadWithComponents(n.getCompound("data"),level.registryAccess());if(net.neoforged.fml.ModList.get().isLoaded("sophisticatedstorage"))dev.jco.upgrades.integration.SophisticatedStorage.restoreWoodFromSnapshot(be,n.getCompound("data"));be.setChanged();level.sendBlockUpdated(pos,state,state,3);}}finally{UpgradeRuntime.TRANSFORMING.remove();}
  data.history.remove(pos.asLong());if(n.contains("previous"))data.history.put(pos.asLong(),n.getCompound("previous").copy());data.setDirty();for(var raw:n.getList("materials",10)){var stack=ItemStack.parseOptional(level.registryAccess(),(CompoundTag)raw);if(!p.getInventory().add(stack))p.drop(stack,false);}new Feedback().particles("minecraft:happy_villager",12,.4,.03).emit(level,Vec3.atCenterOf(pos),p,InteractionHand.MAIN_HAND,state.getBlock().asItem().getDefaultInstance(),false);
 }
 public static CompoundTag view(ServerLevel level,BlockPos pos){var n=valid(level,pos);if(n.isEmpty())return new CompoundTag();var state=NbtUtils.readBlockState(level.holderLookup(Registries.BLOCK),n.getCompound("source"));var out=new CompoundTag();out.putBoolean("reverse",true);out.putString("tool",n.getString("tool"));out.putString("id","reverse:"+n.getString("target"));out.putString("title",state.getBlock().getName().getString());out.putString("description","Right-click to undo / refund");out.putDouble("range",6);out.put("icon",state.getBlock().asItem().getDefaultInstance().saveOptional(level.registryAccess()));var rows=new ListTag();var row=new CompoundTag();var matcher=new StackMatcher(n.getString("tool"));var display=UpgradeRuntime.representative(matcher);row.put("icon",display.saveOptional(level.registryAccess()));row.putString("label",UpgradeRuntime.label(matcher,display));row.putString("input","RIGHT");row.putInt("have",n.getInt("hits"));row.putInt("need",n.getInt("need"));rows.add(row);out.put("rows",rows);return out;}
}
