package dev.jco.upgrades.client;
import dev.jco.upgrades.ImpactPayload;import java.util.*;import net.minecraft.client.Minecraft;import net.minecraft.client.renderer.*;import net.minecraft.core.BlockPos;import net.neoforged.neoforge.client.event.*;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.api.distmarker.Dist;
/** Always-visible bounded response, independent of the optional animation provider. */
@EventBusSubscriber(modid="jco_upgrades",value=Dist.CLIENT) public final class ImpactPulse {
 private record Pulse(ImpactPayload value,long started){}private static final Map<BlockPos,Pulse> pulses=new HashMap<>();
 public static void accept(ImpactPayload p){if(pulses.size()>128)pulses.clear();pulses.put(p.pos(),new Pulse(p,System.nanoTime()));}
 @SubscribeEvent public static void logout(ClientPlayerNetworkEvent.LoggingOut e){pulses.clear();}
 @SubscribeEvent public static void render(RenderLevelStageEvent e){if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_BLOCK_ENTITIES)return;var mc=Minecraft.getInstance();if(mc.level==null){pulses.clear();return;}long now=System.nanoTime();pulses.values().removeIf(p->!p.value.dimension().equals(mc.level.dimension().location().toString())||now-p.started>p.value.ticks()*50000000L);var buffers=mc.renderBuffers().bufferSource();var lines=buffers.getBuffer(RenderType.lines());var camera=e.getCamera().getPosition();for(var pulse:pulses.values()){var pos=pulse.value.pos();if(!mc.level.hasChunkAt(pos))continue;var shape=mc.level.getBlockState(pos).getShape(mc.level,pos);if(shape.isEmpty())continue;double age=(now-pulse.started)/(pulse.value.ticks()*50000000D);double wave=Math.sin(age*Math.PI)*(1-age);var bounds=shape.bounds().inflate(.004+pulse.value.amplitude()*wave*.35).move(pos.getX()-camera.x,pos.getY()-camera.y,pos.getZ()-camera.z);LevelRenderer.renderLineBox(e.getPoseStack(),lines,bounds,.8F,.73F,.53F,(float)((1-age)*.7));}buffers.endBatch(RenderType.lines());}
}
